kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-viewweb
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-editweb
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]