kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-viewapi-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-viewapi
subjects:
- kind: User 
  namespace: api
  name: webdev@msftopenhack6776ops.onmicrosoft.com

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-editweb-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-editweb
subjects:
- kind: User
  namespace: web
  name: webdev@msftopenhack6776ops.onmicrosoft.com