---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity
  namespace: api
spec:
  parameters:
    keyvaultName: team4ProdKeyVault
    objects: |
      array:
        - |
          objectName: SQLUSER
          objectType: secret        # object types: secret, key, or cert
        - |
          objectName: SQLPASSWORD
          objectType: secret
    tenantId: 772c4cf0-acfd-4ffc-aede-7af5637622dc
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 16c8a9bf-8e68-469d-b920-7b115985bd62
  provider: azure
  secretObjects:
  - data:
    - key: SQLUSER
      objectName: SQLUSER
    - key: SQLPASSWORD
      objectName: SQLPASSWORD
    secretName: azure-kvname-workload-identity
    type: Opaque
