apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryidw6538.azurecr.io/tripinsights/trips:1.0
        #imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserveridw6538.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        envFrom:
        - secretRef:
            name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
  labels:
    app: trips
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: trips
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trips-ingress
  namespace: api

  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: 4cc0c5dafc854b8785bc.eastasia.aksapp.io
    http:
      paths:
      - path: /api/trips
        pathType: Prefix
        backend:
          service: 
            name: trips-service
            port: 
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service: 
            name: trips-service
            port: 
              number: 80
      - path: /api/docs/trips
        pathType: Prefix
        backend:
          service: 
            name: trips-service
            port: 
              number: 80
      - path: /api/json
        pathType: Prefix
        backend:
          service: 
            name: trips-service
            port: 
              number: 80
