apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryidw6538.azurecr.io/tripinsights/tripviewer:1.0
        #imagePullPolicy: Always 
        ports:
        - containerPort: 80