apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  namespace: api
  labels:
    app: userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registryidw6538.azurecr.io/tripinsights/user-java:1.0
        #imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserveridw6538.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: SQL_PASSWORD
        
---
apiVersion: v1
kind: Service
metadata:
  name: userjava-service
  namespace: api
  labels:
    app: userjava
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: userjava
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userjava-ingress
  namespace: api

  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: 4cc0c5dafc854b8785bc.eastasia.aksapp.io
    http:
      paths:
      - path: /api/user-java
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80
      - path: /api/metrics
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80
      - path: /api/docs/user-java
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80
      - path: /api/documentation/user-java
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80
      - path: /api/swagger-resources
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80
      - path: /api/api-docs
        pathType: Prefix
        backend:
          service: 
            name: userjava-service
            port: 
              number: 80