apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryidw6538.azurecr.io/tripinsights/userprofile:1.0
        #imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: "sqlserveridw6538.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        envFrom:
        - secretRef:
            name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
  labels:
    app: userprofile
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: userprofile